project_id: qirim-young-website
api_token_env: CROWDIN_API_TOKEN
base_path: .
base_url: 'https://api.crowdin.com'
preserve_hierarchy: 1
files:
  - source: /src/i18n/locales/crh.json
    translation: /src/i18n/locales/%two_letters_code%.json
    languages_mapping:
      two_letters_code:
        uk: uk
        en: en
