# Crowdin configuration for QIRI'M YOUNG Website
# Project Type: File-based Software Localization

project_id: "qirim-young-website"
api_token_env: "CROWDIN_API_TOKEN"
base_path: "."
base_url: "https://api.crowdin.com"

preserve_hierarchy: true

files:
  - source: "/src/i18n/locales/uk.json"
    translation: "/src/i18n/locales/%three_letters_code%.json"
    languages_mapping:
      three_letters_code:
        crh: "crh"
        eng: "en"
    
# Translation workflow
# 1. Source: Ukrainian (uk) - maintained by QIRI'M YOUNG team
# 2. Targets: Crimean Tatar (crh), English (en) - community/professional translations
# 3. Auto-sync with GitHub via webhook

# Commands:
# Upload sources: crowdin upload sources
# Download translations: crowdin download
# Build translations: crowdin build
