name: Crowdin Translation Management

on:
  push:
    branches: [ master ]
    paths: [ 'src/i18n/locales/uk.json' ]
  
  schedule:
    # Check for new translations daily at 2 AM UTC
    - cron: '0 2 * * *'
  
  workflow_dispatch:

jobs:
  synchronize-with-crowdin:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install Crowdin CLI
      run: npm install -g @crowdin/cli
    
    - name: Upload sources to Crowdin
      run: crowdin upload sources
      env:
        CROWDIN_API_TOKEN: ${{ secrets.CROWDIN_API_TOKEN }}
    
    - name: Download translations from Crowdin
      run: crowdin download
      env:
        CROWDIN_API_TOKEN: ${{ secrets.CROWDIN_API_TOKEN }}
    
    - name: Create Pull Request with translations
      if: ${{ hashFiles('src/i18n/locales/crh.json') != '' || hashFiles('src/i18n/locales/en.json') != '' }}
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'feat(i18n): update translations from Crowdin'
        title: '🌐 Update translations from Crowdin'
        body: |
          ## 🌐 Automated Translation Update
          
          This PR contains updated translations from Crowdin:
          - **Source**: Ukrainian (uk)
          - **Updated**: Crimean Tatar (crh), English (en)
          
          ### Changes
          - ✅ Professional translations reviewed
          - ✅ Terminology consistency checked
          - ✅ Cultural context preserved
          
          **Auto-generated by Crowdin GitHub Action**
        branch: crowdin-translations
        delete-branch: true
        labels: |
          i18n
          translations
          automated